---
- file: path=~/deploy state=directory

- template: src=templates/{{ item }} dest=~/deploy/{{ item }}
  with_items:
    - docker-compose.yml
    - nginx.conf

- synchronize: src=app dest=deploy # Very ugly line, don't do it on production. It's better to pull an image from registry.
